{
    "userInfo": {
        "institute": false,
        "member": false,
        "individual": false,
        "guest": false,
        "subscribedContent": false,
        "fileCabinetContent": false,
        "fileCabinetUser": false,
        "institutionalFileCabinetUser": false,
        "showPatentCitations": true,
        "showGet802Link": false
    },
    "records": [{
        "patentCitationCount": 0,
        "accessType": {
            "type": "ephemera",
            "message": "Freely Available from IEEE"
        },
        "articleNumber": "8802303",
        "doi": "10.1109/MPE.2019.2914792",
        "citationCount": 0,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": false,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "781",
        "startPage": "C1",
        "endPage": "C1",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=Front+Cover&isbn=null&publicationDate=Sept.-Oct.+2019&author=&ContentID=10.1109/MPE.2019.2914792&orderBeanReset=true&startPage=C1&endPage=C1&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": true,
        "vj": false,
        "articleTitle": "Front Cover",
        "downloadCount": 161,
        "htmlLink": "/document/8802303/",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "Presents the front cover for this issue of the publication.",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802303",
        "highlightedTitle": "Front Cover",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "patentCitationCount": 0,
        "accessType": {
            "type": "ephemera",
            "message": "Freely Available from IEEE"
        },
        "articleNumber": "8802356",
        "doi": "10.1109/MPE.2019.2914793",
        "citationCount": 0,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": false,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "363",
        "startPage": "1",
        "endPage": "1",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=Table+of+Contents&isbn=null&publicationDate=Sept.-Oct.+2019&author=&ContentID=10.1109/MPE.2019.2914793&orderBeanReset=true&startPage=1&endPage=1&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": true,
        "vj": false,
        "articleTitle": "Table of Contents",
        "downloadCount": 142,
        "htmlLink": "/document/8802356/",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "Presents the table of contents for this issue of the publication.",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802356",
        "highlightedTitle": "Table of Contents",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "patentCitationCount": 0,
        "accessType": {
            "type": "ephemera",
            "message": "Freely Available from IEEE"
        },
        "articleNumber": "8802342",
        "doi": "10.1109/MPE.2019.2914794",
        "citationCount": 0,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": false,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "165",
        "startPage": "2",
        "endPage": "2",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=Staff+Listing&isbn=null&publicationDate=Sept.-Oct.+2019&author=&ContentID=10.1109/MPE.2019.2914794&orderBeanReset=true&startPage=2&endPage=2&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": true,
        "vj": false,
        "articleTitle": "Staff Listing",
        "downloadCount": 58,
        "htmlLink": "/document/8802342/",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "Presents a listing of the editorial board, board of governors, current staff, committee members, and/or society editors for this issue of the publication.",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802342",
        "highlightedTitle": "Staff Listing",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "authors": [{
            "preferredName": "Michael Henderson",
            "normalizedName": "M. Henderson",
            "firstName": "Michael",
            "lastName": "Henderson",
            "searchablePreferredName": "Michael Henderson",
            "id": 37085783182
        }],
        "patentCitationCount": 0,
        "accessType": {
            "type": "ephemera",
            "message": "Freely Available from IEEE"
        },
        "articleNumber": "8802326",
        "doi": "10.1109/MPE.2019.2921846",
        "citationCount": 0,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": true,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "801",
        "startPage": "4",
        "endPage": "6",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=Many+Questions%3A+Grid+Architecture+Provides+Answers+%5BFrom+the+Editor%5D&isbn=null&publicationDate=Sept.-Oct.+2019&author=Michael+Henderson&ContentID=10.1109/MPE.2019.2921846&orderBeanReset=true&startPage=4&endPage=6&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": true,
        "vj": false,
        "articleTitle": "Many Questions: Grid Architecture Provides Answers [From the Editor]",
        "downloadCount": 135,
        "htmlLink": "/document/8802326/",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "Presents the introductory editorial for this issue of the publication.",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802326",
        "highlightedTitle": "Many Questions: Grid Architecture Provides Answers [From the Editor]",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "authors": [{
            "preferredName": "Farnoosh Rahmatian",
            "normalizedName": "F. Rahmatian",
            "firstName": "Farnoosh",
            "lastName": "Rahmatian",
            "searchablePreferredName": "Farnoosh Rahmatian"
        }],
        "patentCitationCount": 0,
        "accessType": {
            "type": "ephemera",
            "message": "Freely Available from IEEE"
        },
        "documentLink": "/document/8802327/",
        "articleNumber": "8802327",
        "doi": "10.1109/MPE.2019.2921847",
        "citationCount": 0,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": false,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "929",
        "startPage": "8",
        "endPage": "12",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=Our+Technical+Committees%3A+At+the+Heart+of+PES+Technical+Activities+%5BLeader%27s+Corner%5D&isbn=null&publicationDate=Sept.-Oct.+2019&author=Farnoosh+Rahmatian&ContentID=10.1109/MPE.2019.2921847&orderBeanReset=true&startPage=8&endPage=12&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": true,
        "vj": false,
        "articleTitle": "Our Technical Committees: At the Heart of PES Technical Activities [Leader's Corner]",
        "downloadCount": 83,
        "htmlLink": "/document/8802327/",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "Reports on PES society technical activities, committees, and events.",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802327",
        "highlightedTitle": "Our Technical Committees: At the Heart of PES Technical Activities [Leader's Corner]",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "authors": [{
            "preferredName": "Steve Widergren",
            "normalizedName": "S. Widergren",
            "firstName": "Steve",
            "lastName": "Widergren",
            "searchablePreferredName": "Steve Widergren",
            "id": 37281614100
        }, {
            "preferredName": "Jeffrey D. Taft",
            "normalizedName": "J. D. Taft",
            "firstName": "Jeffrey D.",
            "lastName": "Taft",
            "searchablePreferredName": "Jeffrey D. Taft",
            "id": 38235514400
        }],
        "patentCitationCount": 0,
        "accessType": {
            "type": "ephemera",
            "message": "Freely Available from IEEE"
        },
        "articleNumber": "8802331",
        "doi": "10.1109/MPE.2019.2921848",
        "citationCount": 1,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": true,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "340",
        "startPage": "14",
        "endPage": "16",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=Grid+Architecture%3A+The+Decisions+That+Will+Shape+Our+Energy+Future+%5BGuest+Editorial%5D&isbn=null&publicationDate=Sept.-Oct.+2019&author=Steve+Widergren%3B+Jeffrey+D.+Taft&ContentID=10.1109/MPE.2019.2921848&orderBeanReset=true&startPage=14&endPage=16&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": true,
        "vj": false,
        "articleTitle": "Grid Architecture: The Decisions That Will Shape Our Energy Future [Guest Editorial]",
        "downloadCount": 286,
        "htmlLink": "/document/8802331/",
        "citationsLink": "/document/8802331/citations?tabFilter=papers",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "The six articles in this special section focus on power grid systems architecture. Complex systems such as power systems are composed of many elements. Architecture concerns itself with how to manage the entire ensemble of elements that make up a system. When we think of an architecture for electric power systems, the concepts need to go beyond addressing how the elements of these systems interope...",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802331",
        "highlightedTitle": "Grid Architecture: The Decisions That Will Shape Our Energy Future [Guest Editorial]",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "patentCitationCount": 0,
        "accessType": {
            "type": "ephemera",
            "message": "Freely Available from IEEE"
        },
        "articleNumber": "8802300",
        "doi": "10.1109/MPE.2019.2929730",
        "citationCount": 0,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": false,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "614",
        "startPage": "15",
        "endPage": "15",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=IEEE+PES+APPEEC&isbn=null&publicationDate=Sept.-Oct.+2019&author=&ContentID=10.1109/MPE.2019.2929730&orderBeanReset=true&startPage=15&endPage=15&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": true,
        "vj": false,
        "articleTitle": "IEEE PES APPEEC",
        "downloadCount": 102,
        "htmlLink": "/document/8802300/",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "Presents information on the IEEE PES APPEEC conference.",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802300",
        "highlightedTitle": "IEEE PES APPEEC",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "patentCitationCount": 0,
        "accessType": {
            "type": "ephemera",
            "message": "Freely Available from IEEE"
        },
        "articleNumber": "8802334",
        "doi": "10.1109/MPE.2019.2929726",
        "citationCount": 0,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": false,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "577",
        "startPage": "17",
        "endPage": "17",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=2019+ISGT&isbn=null&publicationDate=Sept.-Oct.+2019&author=&ContentID=10.1109/MPE.2019.2929726&orderBeanReset=true&startPage=17&endPage=17&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": true,
        "vj": false,
        "articleTitle": "2019 ISGT",
        "downloadCount": 62,
        "htmlLink": "/document/8802334/",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "Presents information on the 2019 ISGT conference.",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802334",
        "highlightedTitle": "2019 ISGT",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "authors": [{
            "preferredName": "Jeffrey D. Taft",
            "normalizedName": "J. D. Taft",
            "firstName": "Jeffrey D.",
            "lastName": "Taft",
            "searchablePreferredName": "Jeffrey D. Taft",
            "id": 38235514400
        }],
        "patentCitationCount": 0,
        "accessType": {
            "type": "locked",
            "message": "Full text access may be available. Click article title to sign in or learn about subscription options."
        },
        "documentLink": "/document/8802341/",
        "articleNumber": "8802341",
        "doi": "10.1109/MPE.2019.2921739",
        "citationCount": 4,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": true,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "2834",
        "startPage": "18",
        "endPage": "28",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=Grid+Architecture%3A+A+Core+Discipline+for+Grid+Modernization&isbn=null&publicationDate=Sept.-Oct.+2019&author=Jeffrey+D.+Taft&ContentID=10.1109/MPE.2019.2921739&orderBeanReset=true&startPage=18&endPage=28&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": false,
        "vj": false,
        "articleTitle": "Grid Architecture: A Core Discipline for Grid Modernization",
        "downloadCount": 483,
        "htmlLink": "/document/8802341/",
        "citationsLink": "/document/8802341/citations?tabFilter=papers",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "By the beginning of the present decade, it had become clear that efforts to improve U.S. electric power systems as well as power systems around the world were being stymied by a problem that was more or less recognized but not often articulated: the overwhelming complexity of what is generally and loosely referred to as the grid had become so great that understanding the implications of changes to...",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802341",
        "highlightedTitle": "Grid Architecture: A Core Discipline for Grid Modernization",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "authors": [{
            "preferredName": "Paul De Martini",
            "normalizedName": "P. De Martini",
            "firstName": "Paul",
            "lastName": "De Martini",
            "searchablePreferredName": "Paul De Martini",
            "id": 38599264100
        }],
        "patentCitationCount": 0,
        "accessType": {
            "type": "locked",
            "message": "Full text access may be available. Click article title to sign in or learn about subscription options."
        },
        "documentLink": "/document/8802328/",
        "articleNumber": "8802328",
        "doi": "10.1109/MPE.2019.2921740",
        "citationCount": 3,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": true,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "1628",
        "startPage": "29",
        "endPage": "39",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=Operational+Coordination+Architecture%3A+New+Models+and+Approaches&isbn=null&publicationDate=Sept.-Oct.+2019&author=Paul+De+Martini&ContentID=10.1109/MPE.2019.2921740&orderBeanReset=true&startPage=29&endPage=39&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": false,
        "vj": false,
        "articleTitle": "Operational Coordination Architecture: New Models and Approaches",
        "downloadCount": 337,
        "htmlLink": "/document/8802328/",
        "citationsLink": "/document/8802328/citations?tabFilter=papers",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "The Growing use of distributed energy resource (DER) services from distributed generation, storage, flexible loads, energy efficiency, and electric vehicles is driving a need for increased coordination among transmission and distribution operators (DOs), customers, aggregators, and a variety of emerging participants. To ensure a reliable and resilient power grid today and into the future, it is es...",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802328",
        "highlightedTitle": "Operational Coordination Architecture: New Models and Approaches",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "authors": [{
            "preferredName": "Marc Asano",
            "normalizedName": "M. Asano",
            "firstName": "Marc",
            "lastName": "Asano",
            "searchablePreferredName": "Marc Asano",
            "id": 37086219007
        }],
        "patentCitationCount": 0,
        "accessType": {
            "type": "locked",
            "message": "Full text access may be available. Click article title to sign in or learn about subscription options."
        },
        "documentLink": "/document/8802333/",
        "articleNumber": "8802333",
        "doi": "10.1109/MPE.2019.2921741",
        "citationCount": 3,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": true,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "1405",
        "startPage": "40",
        "endPage": "46",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=Hawai%27i%27s+Grid+Architecture+for+High+Renewables%3A+Developing+the+State%27s+Modernization+Strategy&isbn=null&publicationDate=Sept.-Oct.+2019&author=Marc+Asano&ContentID=10.1109/MPE.2019.2921741&orderBeanReset=true&startPage=40&endPage=46&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": false,
        "vj": false,
        "articleTitle": "Hawai'i's Grid Architecture for High Renewables: Developing the State's Modernization Strategy",
        "downloadCount": 279,
        "htmlLink": "/document/8802333/",
        "citationsLink": "/document/8802333/citations?tabFilter=papers",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "The Hawailan electric companies the United States in private rooftop solar adoption, with 30% of single-family homes pushing electricity onto the grid. The grid of the future must better accommodate this two-way flow of energy, which is why Hawaiian Electric, Maui Electric, and Hawai&#39;i Electric Light developed a comprehensive grid modernization strategy. &#34;Modernizing Hawai&#39;i&#39;s Grid for Our Custome...",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802333",
        "highlightedTitle": "Hawai'i's Grid Architecture for High Renewables: Developing the State's Modernization Strategy",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "authors": [{
            "preferredName": "Steve Widergren",
            "normalizedName": "S. Widergren",
            "firstName": "Steve",
            "lastName": "Widergren",
            "searchablePreferredName": "Steve Widergren",
            "id": 37281614100
        }, {
            "preferredName": "Ron Melton",
            "normalizedName": "R. Melton",
            "firstName": "Ron",
            "lastName": "Melton",
            "searchablePreferredName": "Ron Melton",
            "id": 37602531000
        }, {
            "preferredName": "Aditya Khandekar",
            "normalizedName": "A. Khandekar",
            "firstName": "Aditya",
            "lastName": "Khandekar",
            "searchablePreferredName": "Aditya Khandekar",
            "id": 37086059492
        }, {
            "preferredName": "Bruce Nordman",
            "normalizedName": "B. Nordman",
            "firstName": "Bruce",
            "lastName": "Nordman",
            "searchablePreferredName": "Bruce Nordman",
            "id": 37282030000
        }, {
            "preferredName": "Mark Knight",
            "normalizedName": "M. Knight",
            "firstName": "Mark",
            "lastName": "Knight",
            "searchablePreferredName": "Mark Knight",
            "id": 37085875645
        }],
        "patentCitationCount": 0,
        "accessType": {
            "type": "locked",
            "message": "Full text access may be available. Click article title to sign in or learn about subscription options."
        },
        "documentLink": "/document/8802361/",
        "articleNumber": "8802361",
        "doi": "10.1109/MPE.2019.2921742",
        "citationCount": 3,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": true,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "2312",
        "startPage": "47",
        "endPage": "58",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=The+Plug-and-Play+Electricity+Era%3A+Interoperability+to+Integrate+Anything%2C+Anywhere%2C+Anytime&isbn=null&publicationDate=Sept.-Oct.+2019&author=Steve+Widergren%3B+Ron+Melton%3B+Aditya+Khandekar%3B+Bruce+Nordman%3B+Mark+Knight&ContentID=10.1109/MPE.2019.2921742&orderBeanReset=true&startPage=47&endPage=58&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": false,
        "vj": false,
        "articleTitle": "The Plug-and-Play Electricity Era: Interoperability to Integrate Anything, Anywhere, Anytime",
        "downloadCount": 553,
        "htmlLink": "/document/8802361/",
        "citationsLink": "/document/8802361/citations?tabFilter=papers",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "The inforrmation age continues to transform the mechanics of integrating electric power devices and systems, from coordinated operations based purely on the physics of electric power engineering to an increasing blend of power with information and communication technology. Integrating electric system components is not just about attaching wires. It requires the connection of computer-based automat...",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802361",
        "highlightedTitle": "The Plug-and-Play Electricity Era: Interoperability to Integrate Anything, Anywhere, Anytime",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "authors": [{
            "preferredName": "Abo Rassa",
            "normalizedName": "A. Rassa",
            "firstName": "Abo",
            "lastName": "Rassa",
            "searchablePreferredName": "Abo Rassa",
            "id": 37086941935
        }, {
            "preferredName": "Coen van Leeuwen",
            "normalizedName": "C. van Leeuwen",
            "firstName": "Coen",
            "lastName": "van Leeuwen",
            "searchablePreferredName": "Coen van Leeuwen",
            "id": 37086942796
        }, {
            "preferredName": "Robertjan Spaans",
            "normalizedName": "R. Spaans",
            "firstName": "Robertjan",
            "lastName": "Spaans",
            "searchablePreferredName": "Robertjan Spaans",
            "id": 37086939285
        }, {
            "preferredName": "Koen Kok",
            "normalizedName": "K. Kok",
            "firstName": "Koen",
            "lastName": "Kok",
            "searchablePreferredName": "Koen Kok",
            "id": 37284956300
        }],
        "patentCitationCount": 0,
        "accessType": {
            "type": "locked",
            "message": "Full text access may be available. Click article title to sign in or learn about subscription options."
        },
        "documentLink": "/document/8802349/",
        "articleNumber": "8802349",
        "doi": "10.1109/MPE.2019.2921743",
        "citationCount": 3,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": true,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "1858",
        "startPage": "59",
        "endPage": "70",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=Developing+Local+Energy+Markets%3A+A+Holistic+System+Approach&isbn=null&publicationDate=Sept.-Oct.+2019&author=Abo+Rassa%3B+Coen+van+Leeuwen%3B+Robertjan+Spaans%3B+Koen+Kok&ContentID=10.1109/MPE.2019.2921743&orderBeanReset=true&startPage=59&endPage=70&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": false,
        "vj": false,
        "articleTitle": "Developing Local Energy Markets: A Holistic System Approach",
        "downloadCount": 473,
        "htmlLink": "/document/8802349/",
        "citationsLink": "/document/8802349/citations?tabFilter=papers",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "Currently, the energy system is transforming in an unprecedented manner due to decentralization and decarbonization. A third clear development is so-called sector coupling, which refers to the growing interdependency of the electricity, heat/cooling, and transport sectors caused by overlapping infrastructure and using storable energy sources.",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802349",
        "highlightedTitle": "Developing Local Energy Markets: A Holistic System Approach",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "authors": [{
            "preferredName": "Steffi O. Muhanji",
            "normalizedName": "S. O. Muhanji",
            "firstName": "Steffi O.",
            "lastName": "Muhanji",
            "searchablePreferredName": "Steffi O. Muhanji",
            "id": 37086406763
        }, {
            "preferredName": "Wester C.H. Schoonenberg",
            "normalizedName": "W. C. H. Schoonenberg",
            "firstName": "Wester C.H.",
            "lastName": "Schoonenberg",
            "searchablePreferredName": "Wester C.H. Schoonenberg",
            "id": 37085655445
        }, {
            "preferredName": "Amro M. Farid",
            "normalizedName": "A. M. Farid",
            "firstName": "Amro M.",
            "lastName": "Farid",
            "searchablePreferredName": "Amro M. Farid",
            "id": 38665664100
        }],
        "patentCitationCount": 0,
        "accessType": {
            "type": "locked",
            "message": "Full text access may be available. Click article title to sign in or learn about subscription options."
        },
        "documentLink": "/document/8802352/",
        "articleNumber": "8802352",
        "doi": "10.1109/MPE.2019.2921744",
        "citationCount": 1,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": true,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "2455",
        "startPage": "71",
        "endPage": "81",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=Transforming+the+Grid%27s+Architecture%3A+Enterprise+Control%2C+the+Energy+Internet+of+Things%2C+and+Heterofunctional+Graph+Theory&isbn=null&publicationDate=Sept.-Oct.+2019&author=Steffi+O.+Muhanji%3B+Wester+C.H.+Schoonenberg%3B+Amro+M.+Farid&ContentID=10.1109/MPE.2019.2921744&orderBeanReset=true&startPage=71&endPage=81&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": false,
        "vj": false,
        "articleTitle": "Transforming the Grid's Architecture: Enterprise Control, the Energy Internet of Things, and Heterofunctional Graph Theory",
        "downloadCount": 278,
        "htmlLink": "/document/8802352/",
        "citationsLink": "/document/8802352/citations?tabFilter=papers",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "The electric power grid was developed on an implicit architectural assumption of centralized dispatchable generation serving all of customers' passive distributed loads irrespective of the operating costs required to do so.",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802352",
        "highlightedTitle": "Transforming the Grid's Architecture: Enterprise Control, the Energy Internet of Things, and Heterofunctional Graph Theory",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "authors": [{
            "preferredName": "Adam Allerhand",
            "normalizedName": "A. Allerhand",
            "firstName": "Adam",
            "lastName": "Allerhand",
            "searchablePreferredName": "Adam Allerhand",
            "id": 37086176942
        }],
        "patentCitationCount": 0,
        "accessType": {
            "type": "locked",
            "message": "Full text access may be available. Click article title to sign in or learn about subscription options."
        },
        "documentLink": "/document/8802330/",
        "articleNumber": "8802330",
        "doi": "10.1109/MPE.2019.2921059",
        "citationCount": 0,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": true,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "9138",
        "startPage": "82",
        "endPage": "90",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=Early+AC+Power%3A+The+First+Long-Distance+Lines+%5BHistory%5D&isbn=null&publicationDate=Sept.-Oct.+2019&author=Adam+Allerhand&ContentID=10.1109/MPE.2019.2921059&orderBeanReset=true&startPage=82&endPage=90&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": false,
        "vj": false,
        "articleTitle": "Early AC Power: The First Long-Distance Lines [History]",
        "downloadCount": 246,
        "htmlLink": "/document/8802330/",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "In 1883, A 2,000-V, SINGLE-PHASE, 133 1/3-Hz power distribution system, designed and built by French inventor Lucien Gaulard and his British backer John Dixon Gibbs for the Metropolitan Railway of London, stretched for 15 mi and provided electric power for arc and incandescent lights at five railway stations. In 1884, a single-phase, 3,000-V, 133 1/3-Hz Gaulard?Gibbs power distribution system in I...",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802330",
        "highlightedTitle": "Early AC Power: The First Long-Distance Lines [History]",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "patentCitationCount": 0,
        "accessType": {
            "type": "ephemera",
            "message": "Freely Available from IEEE"
        },
        "articleNumber": "8802350",
        "doi": "10.1109/MPE.2019.2918818",
        "citationCount": 0,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": false,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "794",
        "startPage": "91",
        "endPage": "92",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=PES+Awards%3A+Congratulations+to+the+2019+Winners+%5BAwards%5D&isbn=null&publicationDate=Sept.-Oct.+2019&author=&ContentID=10.1109/MPE.2019.2918818&orderBeanReset=true&startPage=91&endPage=92&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": true,
        "vj": false,
        "articleTitle": "PES Awards: Congratulations to the 2019 Winners [Awards]",
        "downloadCount": 83,
        "htmlLink": "/document/8802350/",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "Presents a listing of PES society award recipients for 2019.",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802350",
        "highlightedTitle": "PES Awards: Congratulations to the 2019 Winners [Awards]",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "patentCitationCount": 0,
        "accessType": {
            "type": "ephemera",
            "message": "Freely Available from IEEE"
        },
        "documentLink": "/document/8802325/",
        "articleNumber": "8802325",
        "doi": "10.1109/MPE.2019.2929725",
        "citationCount": 0,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": false,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "767",
        "startPage": "92",
        "endPage": "92",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=IEEE+PES+Resource+Center&isbn=null&publicationDate=Sept.-Oct.+2019&author=&ContentID=10.1109/MPE.2019.2929725&orderBeanReset=true&startPage=92&endPage=92&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": true,
        "vj": false,
        "articleTitle": "IEEE PES Resource Center",
        "downloadCount": 61,
        "htmlLink": "/document/8802325/",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "Advertisement, IEEE.",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802325",
        "highlightedTitle": "IEEE PES Resource Center",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "patentCitationCount": 0,
        "accessType": {
            "type": "ephemera",
            "message": "Freely Available from IEEE"
        },
        "articleNumber": "8802304",
        "doi": "10.1109/MPE.2019.2929729",
        "citationCount": 0,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": false,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "551",
        "startPage": "93",
        "endPage": "93",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=IEEE+PES+Awards&isbn=null&publicationDate=Sept.-Oct.+2019&author=&ContentID=10.1109/MPE.2019.2929729&orderBeanReset=true&startPage=93&endPage=93&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": true,
        "vj": false,
        "articleTitle": "IEEE PES Awards",
        "downloadCount": 50,
        "htmlLink": "/document/8802304/",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "Presents a listing of the PES society award recipients for 2019.",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802304",
        "highlightedTitle": "IEEE PES Awards",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "patentCitationCount": 0,
        "accessType": {
            "type": "ephemera",
            "message": "Freely Available from IEEE"
        },
        "articleNumber": "8802354",
        "doi": "10.1109/MPE.2019.2914783",
        "citationCount": 0,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": true,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "350",
        "startPage": "94",
        "endPage": "95",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=In+Memoriam%3A+William+F.+%28Bill%29+Tinney+%281921-2019%29+%5BObituary%5D&isbn=null&publicationDate=Sept.-Oct.+2019&author=&ContentID=10.1109/MPE.2019.2914783&orderBeanReset=true&startPage=94&endPage=95&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": true,
        "vj": false,
        "articleTitle": "In Memoriam: William F. (Bill) Tinney (1921-2019) [Obituary]",
        "downloadCount": 300,
        "htmlLink": "/document/8802354/",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "Recounts the career and contributions of William F. TInney.",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802354",
        "highlightedTitle": "In Memoriam: William F. (Bill) Tinney (1921-2019) [Obituary]",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "patentCitationCount": 0,
        "accessType": {
            "type": "ephemera",
            "message": "Freely Available from IEEE"
        },
        "articleNumber": "8802301",
        "doi": "10.1109/MPE.2019.2929727",
        "citationCount": 0,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": false,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "193",
        "startPage": "95",
        "endPage": "95",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=ISGT+2020&isbn=null&publicationDate=Sept.-Oct.+2019&author=&ContentID=10.1109/MPE.2019.2929727&orderBeanReset=true&startPage=95&endPage=95&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": true,
        "vj": false,
        "articleTitle": "ISGT 2020",
        "downloadCount": 67,
        "htmlLink": "/document/8802301/",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "Presents information on the ISGT 2020 conference.",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802301",
        "highlightedTitle": "ISGT 2020",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "patentCitationCount": 0,
        "accessType": {
            "type": "ephemera",
            "message": "Freely Available from IEEE"
        },
        "articleNumber": "8802329",
        "doi": "10.1109/MPE.2019.2921070",
        "citationCount": 0,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": false,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "161",
        "startPage": "96",
        "endPage": "96",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=PES+Meetings%3A+For+More+Information%2C+www.ieee-pes.org+%5BCalendar%5D&isbn=null&publicationDate=Sept.-Oct.+2019&author=&ContentID=10.1109/MPE.2019.2921070&orderBeanReset=true&startPage=96&endPage=96&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": true,
        "vj": false,
        "articleTitle": "PES Meetings: For More Information, www.ieee-pes.org [Calendar]",
        "downloadCount": 44,
        "htmlLink": "/document/8802329/",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "Presents information on upcoming PES society events and meetings.",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802329",
        "highlightedTitle": "PES Meetings: For More Information, www.ieee-pes.org [Calendar]",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "authors": [{
            "preferredName": "Joe Paladino",
            "normalizedName": "J. Paladino",
            "firstName": "Joe",
            "lastName": "Paladino",
            "searchablePreferredName": "Joe Paladino",
            "id": 37086944598
        }],
        "patentCitationCount": 0,
        "accessType": {
            "type": "ephemera",
            "message": "Freely Available from IEEE"
        },
        "articleNumber": "8802335",
        "doi": "10.1109/MPE.2019.2918819",
        "citationCount": 0,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": true,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "520",
        "startPage": "100",
        "endPage": "98",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=Electricity+Infrastructure%3A+The+Application+of+Grid+Architecture+%5BIn+My+View%5D&isbn=null&publicationDate=Sept.-Oct.+2019&author=Joe+Paladino&ContentID=10.1109/MPE.2019.2918819&orderBeanReset=true&startPage=100&endPage=98&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": true,
        "vj": false,
        "articleTitle": "Electricity Infrastructure: The Application of Grid Architecture [In My View]",
        "downloadCount": 119,
        "htmlLink": "/document/8802335/",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "The electric grid has experienced technological and institutional evolution throughout its history. However, we are currently facing a dramatic structural transformation. Five tightly interconnected forces are collectively driving grid transformation, imposing requirements for advanced functional capabilities, and ultimately shaping how utilities and regulators determine effective technology inves...",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802335",
        "highlightedTitle": "Electricity Infrastructure: The Application of Grid Architecture [In My View]",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }, {
        "patentCitationCount": 0,
        "accessType": {
            "type": "ephemera",
            "message": "Freely Available from IEEE"
        },
        "articleNumber": "8802302",
        "doi": "10.1109/MPE.2019.2929724",
        "citationCount": 0,
        "isNumber": "8802299",
        "rightslinkFlag": true,
        "publicationDate": "Sept.-Oct. 2019",
        "showHtml": false,
        "publicationYear": "2019",
        "volume": "17",
        "issue": "5",
        "publicationNumber": "8014",
        "pdfSize": "5409",
        "startPage": "C3",
        "endPage": "C3",
        "rightsLink": "http://s100.copyright.com/AppDispatchServlet?publisherName=ieee&publication=8014&title=IEEE+PES+T%26amp%3BD+Conference+and+Exposition&isbn=null&publicationDate=Sept.-Oct.+2019&author=&ContentID=10.1109/MPE.2019.2929724&orderBeanReset=true&startPage=C3&endPage=C3&volumeNum=17&issueNum=5",
        "publicationLink": "/xpl/RecentIssue.jsp?punumber=8014",
        "showAlgorithm": false,
        "showDataset": false,
        "showVideo": false,
        "ephemera": true,
        "vj": false,
        "articleTitle": "IEEE PES T&amp;D Conference and Exposition",
        "downloadCount": 50,
        "htmlLink": "/document/8802302/",
        "publisher": "IEEE",
        "handleProduct": false,
        "showCheckbox": true,
        "redline": false,
        "contentType": "IEEE Magazines",
        "articleContentType": "Magazines",
        "publicationTitle": "IEEE Power and Energy Magazine",
        "displayPublicationTitle": "IEEE Power and Energy Magazine",
        "abstract": "Presents information on the IEEE PES T&amp;D Conference and Exposition.",
        "pdfLink": "/stamp/stamp.jsp?tp=&arnumber=8802302",
        "highlightedTitle": "IEEE PES T&amp;D Conference and Exposition",
        "isStandard": false,
        "isJournalAndMagazine": true,
        "docIdentifier": "IEEE Magazines",
        "isEarlyAccess": false,
        "isMagazine": false,
        "isJournal": false,
        "isBook": false,
        "course": false,
        "displayContentType": "Magazine Article",
        "isConference": false,
        "isBookWithoutChapters": false
    }],
    "showStandardDictionary": false,
    "searchType": "basic",
    "totalRecords": 23,
    "endRecord": 23,
    "totalPages": 1,
    "startRecord": 0,
    "subscribedContentApplied": false,
    "promoApplied": false,
    "facets": [{
        "id": "Author",
        "name": "Author",
        "numRecords": -1,
        "children": [{
            "id": "Author:Jeffrey D. Taft",
            "name": "Jeffrey D. Taft",
            "numRecords": 2,
            "active": "true"
        }, {
            "id": "Author:Steve Widergren",
            "name": "Steve Widergren",
            "numRecords": 2,
            "active": "true"
        }, {
            "id": "Author:Aditya Khandekar",
            "name": "Aditya Khandekar",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Author:Ron Melton",
            "name": "Ron Melton",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Author:Bruce Nordman",
            "name": "Bruce Nordman",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Author:Robertjan Spaans",
            "name": "Robertjan Spaans",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Author:Paul De Martini",
            "name": "Paul De Martini",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Author:Farnoosh Rahmatian",
            "name": "Farnoosh Rahmatian",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Author:Steffi O. Muhanji",
            "name": "Steffi O. Muhanji",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Author:Wester C.H. Schoonenberg",
            "name": "Wester C.H. Schoonenberg",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Author:Amro M. Farid",
            "name": "Amro M. Farid",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Author:Koen Kok",
            "name": "Koen Kok",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Author:Adam Allerhand",
            "name": "Adam Allerhand",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Author:Abo Rassa",
            "name": "Abo Rassa",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Author:Mark Knight",
            "name": "Mark Knight",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Author:Marc Asano",
            "name": "Marc Asano",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Author:Coen van Leeuwen",
            "name": "Coen van Leeuwen",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Author:Michael Henderson",
            "name": "Michael Henderson",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Author:Joe Paladino",
            "name": "Joe Paladino",
            "numRecords": 1,
            "active": "true"
        }],
        "active": "true"
    }, {
        "id": "Affiliation",
        "name": "Affiliation",
        "numRecords": -1,
        "children": [{
            "id": "Affiliation:Pacific Northwest National Laboratory, Richland, Washington United States",
            "name": "Pacific Northwest National Laboratory, Richland, Washington United States",
            "numRecords": 2,
            "active": "true"
        }, {
            "id": "Affiliation:California Institute of Technology, Pasadena, United States",
            "name": "California Institute of Technology, Pasadena, United States",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Affiliation:Burns and McDonnell, Kansas City, Missouri United States",
            "name": "Burns and McDonnell, Kansas City, Missouri United States",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Affiliation:Lawrence Berkeley National Laboratory, Berkeley, California United States",
            "name": "Lawrence Berkeley National Laboratory, Berkeley, California United States",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Affiliation:Dartmouth College, Hanover, New Hampshire United States",
            "name": "Dartmouth College, Hanover, New Hampshire United States",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Affiliation:The Netherlands Organization for Applied Scientific Research TNO, The Hague, The Netherlands",
            "name": "The Netherlands Organization for Applied Scientific Research TNO, The Hague, The Netherlands",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Affiliation:Hawaiian Electric Companies, Honolulu, United States",
            "name": "Hawaiian Electric Companies, Honolulu, United States",
            "numRecords": 1,
            "active": "true"
        }, {
            "id": "Affiliation:Alliander, Arnhem, The Netherlands",
            "name": "Alliander, Arnhem, The Netherlands",
            "numRecords": 1,
            "active": "true"
        }],
        "active": "true"
    }]
}